### ISSUE TITLE
No repos show up

### ISSUE THREAD

**Issue by podldev** [icyphox/legit#19]
i dont see any repos i put in /var/www/git/
my config:
```yml
repo:
  scanPath: /var/www/git/
  readme:
    - readme
    - README
    - readme.md
    - README.md
  mainBranch:
    - master
    - main
dirs:
  templates: ./templates
  static: ./static
meta:
  title: twegs area
  description: hosts my projects.
server:
  name: no
  host: 0.0.0.0
  port: 5555
```
im using caddy with a config like this:
```caddyfile
no {
        reverse_proxy :5555
}
```

i created the repo with `git init --bare name`
